Vagrant.configure("2") do |config|
  config.vm.box = "rgl/windows-10-1809-enterprise-amd64"
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.memory = "4096"
  end
end